language: php

php:
  - 7.2

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.example .env
  - sudo mysql -e 'CREATE DATABASE laravel58;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
